// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = 8080;

  app.use(express.static(`${__dirname}/public`));

  app.listen(port, function() {
    console.log(`Example app listening at http://localhost:${port}`);
  });

}).call(this);
