// Generated by CoffeeScript 2.5.1
(function() {
  var app, http, io;

  app = require("express")();

  http = require("http").createServer(app);

  io = require("socket.io")(http, {
    cors: {
      origin: "*"
    }
  });

  app.get("/", function(req, res) {
    res.sendFile(`${__dirname}/index.html`);
  });

  io.on("connection", function(socket) {
    console.log("a user connected");
  });

  http.listen(8081, function() {
    console.log("listening on *:8081");
  });

}).call(this);
