// Generated by CoffeeScript 2.5.1
var app, bunny, container, i, j, socket, texture;

import * as PIXI from 'pixi.js';

import io from 'socket.io-client';

socket = io(":8081");

socket.on("connect", function() {
  console.log("CONNECTED!");
  socket.on("disconnect", function() {
    console.log("DISCONNECTED!");
  });
});

app = new PIXI.Application({
  width: window.innerWidth,
  height: window.innerHeight,
  backgroundColor: 0x1099bb,
  resolution: window.devicePixelRatio || 1
});

app.renderer.autoResize = true;

document.body.appendChild(app.view);

container = new PIXI.Container();

app.stage.addChild(container);

// Create a new texture
texture = PIXI.Texture.from('assets/troll.png');

// Create a 5x5 grid of bunnies
for (i = j = 0; j <= 24; i = ++j) {
  bunny = new PIXI.Sprite(texture);
  bunny.anchor.set(0.5);
  bunny.x = (i % 5) * 40;
  bunny.y = Math.floor(i / 5) * 40;
  container.addChild(bunny);
}

// Move container to the center
container.x = app.screen.width / 2;

container.y = app.screen.height / 2;

// Center bunny sprite in local container coordinates
container.pivot.x = container.width / 2;

container.pivot.y = container.height / 2;

// Listen for animate update
app.ticker.add(function(delta) {
  // rotate the container!
  // use delta to create frame-independent transform
  return container.rotation -= 0.01 * delta;
});
